
mean score1 if league=="German Bundesliga", over(season)
mean score1 if league=="German 2. Bundesliga", over(season)
mean score1 if league=="Barclays Premier League", over(season)
mean score1 if league=="English League Championship", over(season)
mean score1 if league=="English League One", over(season)
mean score1 if league=="English League Two", over(season)
mean score1 if league=="Spanish Primera Division", over(season)
mean score1 if league=="Spanish Segunda Division", over(season)	

mean score2 if league=="German Bundesliga", over(season)
mean score2 if league=="German 2. Bundesliga", over(season)
mean score2 if league=="Barclays Premier League", over(season)
mean score2 if league=="English League Championship", over(season)
mean score2 if league=="English League One", over(season)
mean score2 if league=="English League Two", over(season)
mean score2 if league=="Spanish Primera Division", over(season)
mean score2 if league=="Spanish Segunda Division", over(season)	

mean goals if league=="German Bundesliga", over(season)
mean goals if league=="German 2. Bundesliga", over(season)
mean goals if league=="Barclays Premier League", over(season)
mean goals if league=="English League Championship", over(season)
mean goals if league=="English League One", over(season)
mean goals if league=="English League Two", over(season)
mean goals if league=="Spanish Primera Division", over(season)
mean goals if league=="Spanish Segunda Division", over(season)
mean goals if league=="Swedish Allsvenskan", over(season)

mean xGs if league=="German Bundesliga", over(season)
mean xGs if league=="German 2. Bundesliga", over(season)
mean xGs if league=="Barclays Premier League", over(season)
mean xGs if league=="English League Championship", over(season)
mean xGs if league=="English League One", over(season)
mean xGs if league=="English League Two", over(season)
mean xGs if league=="Spanish Primera Division", over(season)
mean xGs if league=="Swedish Allsvenskan", over(season)

mean homewin if league=="German Bundesliga", over(season)
mean homewin if league=="German 2. Bundesliga", over(season)
mean homewin if league=="Barclays Premier League", over(season)
mean homewin if league=="English League Championship", over(season)
mean homewin if league=="English League One", over(season)
mean homewin if league=="English League Two", over(season)
mean homewin if league=="Spanish Primera Division", over(season)
mean homewin if league=="Spanish Segunda Division", over(season)

mean awaywin if league=="German Bundesliga", over(season)
mean awaywin if league=="German 2. Bundesliga", over(season)
mean awaywin if league=="Barclays Premier League", over(season)
mean awaywin if league=="English League Championship", over(season)
mean awaywin if league=="English League One", over(season)
mean awaywin if league=="English League Two", over(season)
mean awaywin if league=="Spanish Primera Division", over(season)
mean awaywin if league=="Spanish Segunda Division", over(season)

mean goaldiff if league=="German Bundesliga", over(season)
mean goaldiff if league=="German 2. Bundesliga", over(season)
mean goaldiff if league=="Barclays Premier League", over(season)
mean goaldiff if league=="English League Championship", over(season)
mean goaldiff if league=="English League One", over(season)
mean goaldiff if league=="English League Two", over(season)
mean goaldiff if league=="Spanish Primera Division", over(season)
mean goaldiff if league=="Spanish Segunda Division", over(season)
mean goaldiff if league=="Spanish Segunda Division", over(season)


mean xGdiff if league=="German Bundesliga", over(season)
mean xGdiff if league=="German 2. Bundesliga", over(season)
mean xGdiff if league=="Barclays Premier League", over(season)
mean xGdiff if league=="English League Championship", over(season)
mean xGdiff if league=="English League One", over(season)
mean xGdiff if league=="English League Two", over(season)
mean xGdiff if league=="Spanish Primera Division", over(season)
mean xGdiff if league=="Spanish Segunda Division", over(season)
